apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sentry
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/ai-hub/sentry
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: platform
    - name: cert-manager
    - name: traefik-config
