apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-kustomizations/external-secrets.yaml
  - flux-kustomizations/cert-manager.yaml
  - flux-kustomizations/traefik.yaml
  - flux-kustomizations/external-dns.yaml
  - flux-kustomizations/cloudflared.yaml
  - flux-kustomizations/vibe-kanban.yaml
