apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: portainer-edge-key
  namespace: portainer
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: portainer-edge-key
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: edge-key
      remoteRef:
        key: ai-hub-secrets
        property: portainer-edge-key-compute-hub
