apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sentry-otlp
  namespace: otel
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: sentry-otlp
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: SENTRY_DSN
      remoteRef:
        key: traefik-edge-dsn
        property: credential
