apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sentry-tls
  namespace: sentry
spec:
  secretName: sentry-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - sentry.nwlnexus.net
