apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sentry-secrets
  namespace: sentry
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: sentry-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: system-secret-key
      remoteRef:
        key: ai-hub-secrets
        property: sentry-system-secret-key
    - secretKey: postgres-password
      remoteRef:
        key: ai-hub-secrets
        property: postgres-password
    - secretKey: clickhouse-password
      remoteRef:
        key: ai-hub-secrets
        property: clickhouse-password
    - secretKey: smtp-password
      remoteRef:
        key: resend
        property: api_key
    - secretKey: admin-username
      remoteRef:
        key: olympus-sentry
        property: username
    - secretKey: admin-password
      remoteRef:
        key: olympus-sentry
        property: password
