provider:
  name: cloudflare
env:
  - name: CF_API_KEY
    valueFrom:
      secretKeyRef:
        name: cloudflare-credentials
        key: api-key
  - name: CF_API_EMAIL
    valueFrom:
      secretKeyRef:
        name: cloudflare-credentials
        key: api-email
domainFilters:
  - nwlnexus.net
policy: sync
sources:
  - service
  - ingress
  - traefik-proxy
txtOwnerId: management-hub
txtPrefix: "mgmt-"
logLevel: info
logFormat: json
extraArgs:
  - --traefik-disable-legacy
  - --cloudflare-proxied
