apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  ts.net.server: |
    raptor-mimosa.ts.net:53 {
        errors
        cache 30
        forward . 100.100.100.100
    }
  portainer.override: |
    dock.nwlnexus.net:53 {
        errors
        hosts {
            100.111.175.126 dock.nwlnexus.net
            fallthrough
        }
        cache 30
    }
