apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - external-endpoints.yaml
  - certificate.yaml
  - ingressroute.yaml
  - relay-certificate.yaml
  - relay-ingressroute.yaml
  - worker-certificate.yaml
  - worker-ingressroute.yaml
