apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: vibe-kanban
  namespace: vibe-kanban
spec:
  interval: 1h
  url: oci://ghcr.io/everythings-gonna-be-alright/charts/vibe-kanban
  ref:
    tag: "0.0.3"
