apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-creds
  namespace: redis
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: redis-creds
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: redis-password
      remoteRef:
        key: management-hub-secrets
        property: redis-password
