apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: qnap-csi-creds
  namespace: trident
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: qnap-csi-creds
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: storageAddress
      remoteRef:
        key: compute-hub-qnap-iscsi
        property: storageAddress
    - secretKey: username
      remoteRef:
        key: compute-hub-qnap-iscsi
        property: username
    - secretKey: password
      remoteRef:
        key: compute-hub-qnap-iscsi
        property: password
    - secretKey: chapInitiatorUsername
      remoteRef:
        key: compute-hub-qnap-iscsi
        property: chapInitiatorUsername
    - secretKey: chapInitiatorPassword
      remoteRef:
        key: compute-hub-qnap-iscsi
        property: chapInitiatorPassword
