apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qnap-csi
  namespace: trident
spec:
  interval: 1h
  chart:
    spec:
      chart: ./Helm/trident
      sourceRef:
        kind: GitRepository
        name: qnap-csi-plugin
        namespace: trident
      interval: 1h
  values:
    tridentOperator:
      image: qnapsystem/qnap-csi-operator:v1.6.0
      cgiServerImage: qnapsystem/qnap-csi-backend-qts-sidecar:v1.6.0
      imagePullPolicy: IfNotPresent
    tridentOrchestrator:
      image: qnapsystem/qnap-csi:v1.6.0
    forceInstallRancherClusterRoles: false
