apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: clickhouse
  namespace: platform
spec:
  interval: 1h
  chart:
    spec:
      chart: clickhouse
      sourceRef:
        kind: HelmRepository
        name: clickhouse
        namespace: platform
  values:
    replicaCount: 1
    auth:
      username: default
      existingSecret: platform-credentials
      existingSecretKey: clickhouse-password
    persistence:
      enabled: true
      existingClaim: clickhouse-data
    extraEnvVars:
      - name: TZ
        value: UTC
