apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgadmin-credentials
  namespace: platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: pgadmin-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: email
      remoteRef:
        key: ai-hub-secrets
        property: pgadmin-email
    - secretKey: password
      remoteRef:
        key: ai-hub-secrets
        property: pgadmin-password
