apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgrest
  namespace: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgrest
  template:
    metadata:
      labels:
        app: postgrest
    spec:
      containers:
        - name: postgrest
          image: postgrest/postgrest:v12.2.3
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: platform-credentials
                  key: postgres-password
            - name: PGRST_DB_URI
              value: "postgresql://postgres:$(POSTGRES_PASSWORD)@postgresql.platform.svc.cluster.local:5432/sentry"
            - name: PGRST_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: platform-credentials
                  key: postgrest-jwt-secret
            - name: PGRST_DB_SCHEMA
              value: public
            - name: PGRST_DB_ANON_ROLE
              value: anon
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: postgrest
  namespace: platform
spec:
  selector:
    app: postgrest
  ports:
    - port: 3000
      targetPort: 3000
