apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: platform
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: qnap-iscsi
  resources:
    requests:
      storage: 50Gi
