apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: redisinsight
  namespace: platform
  annotations:
    external-dns.alpha.kubernetes.io/hostname: redis.nwlnexus.net
    external-dns.alpha.kubernetes.io/target: ing.ai-hub.nwlnexus.net
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`redis.nwlnexus.net`)
      kind: Rule
      services:
        - name: redisinsight
          port: 5540
  tls:
    certResolver: default
