apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redpanda-console
  namespace: platform
spec:
  interval: 1h
  install:
    timeout: 10m
    remediation:
      retries: 3
  chart:
    spec:
      chart: console
      sourceRef:
        kind: HelmRepository
        name: redpanda
        namespace: platform
  values:
    config:
      kafka:
        brokers:
          - kafka.platform.svc.cluster.local:9092
        startup:
          maxRetries: -1
    ingress:
      enabled: false
