apiVersion: v1
kind: Service
metadata:
  name: qnap-ui
  namespace: qnap-ui
spec:
  type: ExternalName
  externalName: qnap.nwlnexus.net
  ports:
    - name: http
      port: 8080
      protocol: TCP
