apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-creds
  namespace: postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: postgres-creds
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: postgres-password
      remoteRef:
        key: management-hub-secrets
        property: postgres-password
