apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
  namespace: clickhouse
data:
  users.xml: |
    <clickhouse>
      <profiles>
        <default>
          <enable_json_type>1</enable_json_type>
          <allow_experimental_object_type>1</allow_experimental_object_type>
        </default>
      </profiles>
    </clickhouse>
