apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: clickhouse-creds
  namespace: clickhouse
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: clickhouse-creds
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: clickhouse-password
      remoteRef:
        key: management-hub-secrets
        property: clickhouse-password
