apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: clickhouse
spec:
  ports:
    - name: http
      port: 8123
      targetPort: 8123
    - name: native
      port: 9000
      targetPort: 9000
  selector:
    app: clickhouse
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-headless
  namespace: clickhouse
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8123
    - name: native
      port: 9000
  selector:
    app: clickhouse
