apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: portainer-agent-secret
  namespace: portainer
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: portainer-agent-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: AGENT_SECRET
      remoteRef:
        key: ai-hub-secrets
        property: portainer-agent-secret
