apiVersion: trident.qnap.io/v1
kind: TridentBackendConfig
metadata:
  name: qnap-management-hub
  namespace: trident
spec:
  version: 1
  storageDriverName: qnap-nas
  backendName: management-hub
  networkInterfaces: ["Adapter1", "Adapter4"]
  userCHAP: true
  credentials:
    name: qnap-csi-creds
  storage:
    - serviceLevel: storage
      labels:
        performance: storage
