apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sentry
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/management-hub/sentry
  prune: true
  wait: true
  timeout: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: postgres
    - name: redis
    - name: kafka
    - name: clickhouse
    - name: cert-manager
