apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-kustomizations/external-secrets.yaml
  - flux-kustomizations/cert-manager.yaml
  - flux-kustomizations/external-dns.yaml
  - flux-kustomizations/cloudflared.yaml
  - flux-kustomizations/traefik-config.yaml
  - flux-kustomizations/litellm.yaml
  - flux-kustomizations/connect-ingress.yaml
  - flux-kustomizations/whoami.yaml
  - flux-kustomizations/qnap-ui.yaml
  - flux-kustomizations/headlamp.yaml
  - flux-kustomizations/kubeconfig-merger.yaml
