apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: connect-tls
  namespace: 1password
spec:
  secretName: connect-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - connect.nwlnexus.net
