apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: headlamp-combined-kubeconfig
  namespace: headlamp
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: headlamp-combined-kubeconfig
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: kubeconfig
      remoteRef:
        key: compute-hub-kubeconfig
        property: document
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
