apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: qnap-trident-backend-creds
  namespace: trident
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: qnap-trident-backend-creds
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        username: "{{ .mgmtUsername }}"
        password: "{{ .mgmtPassword }}"
        storageAddress: "{{ .storageAddress }}"
        https: "false"
        port: "8080"
        chapInitiatorUsername: "{{ .chapInitiatorUsername }}"
        chapInitiatorPassword: "{{ .chapInitiatorPassword }}"
  data:
    - secretKey: mgmtUsername
      remoteRef:
        key: qnap-csi
        property: username
    - secretKey: mgmtPassword
      remoteRef:
        key: qnap-csi
        property: password
    - secretKey: storageAddress
      remoteRef:
        key: ai-hub-qnap-iscsi
        property: storageAddress
    - secretKey: chapInitiatorUsername
      remoteRef:
        key: ai-hub-qnap-iscsi
        property: chapInitiatorUsername
    - secretKey: chapInitiatorPassword
      remoteRef:
        key: ai-hub-qnap-iscsi
        property: chapInitiatorPassword
