apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: qnap-iscsi
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.trident.qnap.io
parameters:
  selector: "location=ai-hub"
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
