apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sentry-secrets
  namespace: sentry
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: sentry-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: postgres-password
      remoteRef:
        key: management-hub-secrets
        property: postgres-password
    - secretKey: redis-password
      remoteRef:
        key: management-hub-secrets
        property: redis-password
    - secretKey: clickhouse-password
      remoteRef:
        key: management-hub-secrets
        property: clickhouse-password
    - secretKey: system-secret-key
      remoteRef:
        key: management-hub-secrets
        property: sentry-system-secret-key
    - secretKey: admin-email
      remoteRef:
        key: management-hub-secrets
        property: sentry-admin-email
    - secretKey: admin-password
      remoteRef:
        key: management-hub-secrets
        property: sentry-admin-password
    - secretKey: resend-api-key
      remoteRef:
        key: resend
        property: api_key
