apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sentry
  namespace: sentry
spec:
  interval: 1h
  timeout: 25m
  chart:
    spec:
      chart: sentry
      version: "31.7.0"
      sourceRef:
        kind: HelmRepository
        name: sentry
        namespace: sentry
  valuesFrom:
    - kind: Secret
      name: sentry-secrets
      valuesKey: system-secret-key
      targetPath: system.secretKey
    - kind: Secret
      name: sentry-secrets
      valuesKey: admin-email
      targetPath: user.email
    - kind: Secret
      name: sentry-secrets
      valuesKey: admin-password
      targetPath: user.password
    - kind: Secret
      name: sentry-secrets
      valuesKey: postgres-password
      targetPath: externalPostgresql.password
    - kind: Secret
      name: sentry-secrets
      valuesKey: redis-password
      targetPath: externalRedis.password
    - kind: Secret
      name: sentry-secrets
      valuesKey: clickhouse-password
      targetPath: externalClickhouse.password
    - kind: Secret
      name: sentry-secrets
      valuesKey: resend-api-key
      targetPath: mail.password
  values:
    postgresql:
      enabled: false
    redis:
      enabled: false
    kafka:
      enabled: false
    clickhouse:
      enabled: false
    zookeeper:
      enabled: false
    rabbitmq:
      enabled: false
    nginx:
      enabled: false

    system:
      url: https://sentry.nwlnexus.net

    externalPostgresql:
      host: postgres-postgresql.postgres.svc.cluster.local
      port: 5432
      username: sentry
      database: sentry

    externalRedis:
      host: redis-master.redis.svc.cluster.local
      port: 6379

    externalKafka:
      host: kafka.kafka.svc.cluster.local
      port: 9092

    externalClickhouse:
      host: clickhouse.clickhouse.svc.cluster.local
      tcpPort: 9000
      httpPort: 8123
      username: default
      clusterName: sentry-clickhouse

    mail:
      backend: smtp
      host: smtp.resend.com
      port: 587
      username: resend
      useTls: true
      useSsl: false
      from: sentry@nwlnexus.io

    filestore:
      backend: filesystem
      filesystem:
        path: /var/lib/sentry/files
      persistence:
        enabled: true
        storageClass: qnap-nfs
        size: 20Gi
