apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: traefik
    repo: https://helm.traefik.io/traefik
    version: "33.0.0"
    releaseName: traefik-tnet
    namespace: traefik-tnet
    valuesFile: values.yaml
