apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qnap-tls
  namespace: traefik-ext
spec:
  secretName: qnap-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - qnap.nwlnexus.net
