apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: portainer-admin
  namespace: portainer
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: portainer-admin
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: username
      remoteRef:
        key: olympus-portainer
        property: username
    - secretKey: password
      remoteRef:
        key: olympus-portainer
        property: password
