apiVersion: v1
kind: Service
metadata:
  name: portainer-edge-ts
  namespace: traefik
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: portainer-edge
    tailscale.com/tags: tag:k8s
spec:
  selector:
    app.kubernetes.io/name: traefik
  ports:
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
    - name: edge
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: LoadBalancer
