apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: capacitor-next
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/gimlet-io/charts/capacitor-next
  ref:
    tag: "0.14.0"
