apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: capacitor-next
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: capacitor-next
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: SESSION_HASH_KEY
      remoteRef:
        key: capacitor-next
        property: session-hash-key
    - secretKey: SESSION_BLOCK_KEY
      remoteRef:
        key: capacitor-next
        property: session-block-key
